package org.group_three.service;


import org.group_three.api.SimController;
import org.group_three.constants.enums.SortDir;
import org.group_three.debug.annotations.MayReturnNull;
import org.group_three.utils.Formatting;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.Comparator;
import java.util.List;
import java.util.function.BinaryOperator;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;


/**<h1>Statistic</h1>
 * Class for 1 singular Statistic, e.g. 1 Graph, 1 Table, etc. <br>
 * Extends to Table
 * @see Table
 * @author Luca
 * */
public class Statistic<T extends Record> extends Table<T> {

    private static final Logger log =
            Logger.getLogger(Statistic.class.getName());

    /// Name to be displayed.
    private String name;
    /// description for when showing the table.
    private String description = "N/A";

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Statistic(String name, String ... atts){
        super(atts);
        this.name = name;
    }

    public Statistic(String name, List<String> atts){
        super(atts);
        this.name = name;
    }

    /**
     * Prints out the Statistic in the following format: <p>
     * <code>name</code>:</p> <p>
     * | Head1  | Head2  | ... <br>
     * ------------------- ...<br>
     * | value1 | value2 | ...<br>
     * | ...</p>
     * @see Table#print()
     * @author Luca
     * */
    @Override
    public void print() throws Exception {
        System.out.println(name + ": ");
        super.print();
    }


    /**
     * Gets the Rows where <code>attribute</code> is <code>target</code><br>
     * @example "statcol" in {@link SimController#queueryStats()}
     * @return The rows as Statistic
     * @param predic The expression to filter for
     * @author Luca
     * */
    public Statistic<T> filter(Predicate<T> predic){

        Statistic<T> stat = new Statistic<>(name + "_filtered", attributeNames);

        for(T rec : content) {
            if(predic.test(rec)) stat.add(rec);
        }

        return stat;
    }

    /**
     * SortDir by the given attribute.
     * @param attribute The name of the attribute you want to sort by.
     * @return A new Statistic, sorted by <code>attribute</code>.
     * @author Luca
     * */
    public <U extends Comparable<? super U>>
    Statistic<T> sortBy(
            Function<? super T, U> attribute
    ) {
        return sortBy(attribute, SortDir.DESC);
    }


    /**
     * SortDir by the given attribute.
     * @param attmethod The method to get the wanted attribute. Autogenerated by Java when creating Records.
     * @param sorttype The direction of the sorting. SortDir.DISC or SortDir.ASC
     * @return A new Statistic, sorted by <code>attribute</code>.
     * @author Luca
     * @see SortDir#ASC
     * @see SortDir#DESC
     * */
    public <U extends Comparable<? super U>>
    Statistic<T> sortBy(
            Function<? super T, U> attmethod,
            SortDir sorttype
    ) {

        List<T> sortcon = content.stream()
                .sorted(
                        Comparator.comparing(attmethod)
                ).toList();

        Statistic<T> outstat = new Statistic<>(name + "sorted", attributeNames);

        if(sorttype == SortDir.ASC) outstat.content = sortcon;
        else outstat.content = sortcon.reversed();

        return outstat;

    }


    /**
     * <p>Aggregates by one Record Component which is passed via its method.</p>
     * <p>The aggregation logic needs to be passed via the aggregator. I tried doing
     * this more generic, with implementation of an Aggregation Interface in the Records,
     * but that would also require to rewrite this class. So it is what it is.</p>
     * @param keyExtractor the "auto-generated" method to extract the Record attribute to aggregate by.
     * @param aggregator The binary operation on < Record, Record >
     * */
    public <K> Statistic<T> aggregate(
            Function<T, K> keyExtractor,
            BinaryOperator<T> aggregator
    ) {
        List<T> agglist = content.stream()
                        .collect(Collectors.toMap(
                                keyExtractor,
                                Function.identity(),
                                aggregator
                        ))
                        .values()
                        .stream()
                        .toList();

        Statistic<T> outstat = new Statistic<>(name + "_aggregated", attributeNames);
        outstat.content = agglist;

        return  outstat;
    }



    /**<h2>outAsZippedCSV</h2>
     * <p> WARNING Creates Files </p>
     * Writes the table to a CSV file into ./output/...
     * @param zos The ZipOutputStream to stream the table content to.
     * @return <code>true</code> if success, <code>false</code> if not.
     * @author Luca
     * */
    public boolean outAsZippedCSV(ZipOutputStream zos) {

        String filename = Formatting.uniquegen(name, ".csv");

        if (content == null || content.isEmpty()) {
            log.warning("Table is empty. " + name + " was not exported.");
            return false;
        }

        try {
            zos.putNextEntry(new ZipEntry(filename));

            // UTF-8 BOM (Excel)
            zos.write(new byte[] {(byte)0xEF, (byte)0xBB, (byte)0xBF});

            Writer writer = new OutputStreamWriter(zos, StandardCharsets.UTF_8);

            writer.write(Formatting.toCSVformat(attributeNames));
            for (T row : content) {
                writer.write(Formatting.toCSVformat(rowToStringList(row)));
            }

            writer.flush();
            zos.closeEntry();

            return true;

        } catch (IOException e) {
            log.warning("Zipping CSV failed: " + e.getMessage());
            return false;
        }
    }

    /**
     * <h2>getGraphOf()</h2>
     * A method that turns a desired table into a Graph, mapping one integer attribute to another.
     *
     * @param x_attribute The name of the attribute that is supposed to be on the x-axis
     * @param y_attribute The name of the attribute that is supposed to be on the y-axis
     * @return a callable function that takes x as an input and returns y.
     * @source <a href="https://stackoverflow.com/a/29584084">Posted by 'satnam' on Stackoverflow</a>
     * @author Luca
     */
    @MayReturnNull
    public Function<Object, Object> getGraphOf(String x_attribute, String y_attribute) {
        // Source - https://stackoverflow.com/a/29584084
        // Posted by satnam, modified by community. See post 'Timeline' for change history
        // Retrieved 2025-12-14, License - CC BY-SA 3.0

        if(!hasAttribute(x_attribute)){
            log.warning(name + ": Attribute \"" + x_attribute + "\" is not a valid attribute of the Table.\n" +
                        "Valid attributes are:\n" +
                        getAttributeNames().toString());
            return null;
        }
        if(!hasAttribute(y_attribute)){
            log.warning(name + ": Attribute \"" + y_attribute + "\" is not a valid attribute of the Table.\n" +
                    "Valid attributes are:\n" +
                    getAttributeNames().toString());
            return null;
        }
        
        List<?> xcolumn = getColumn(x_attribute);
        List<?> ycolumn = getColumn(y_attribute);


        return xval -> {

            int index = xcolumn.indexOf(xval);

            if(index == -1) return null;

            return ycolumn.get(index);
        };

    }



}
